In [1]:
import pandas as pd

In [39]:
merged_data = pd.read_csv('merged_data.csv')

In [40]:
merged_data.head(5)

,date,close,SMA_7,SMA_14,EMA_7,EMA_14,MACD,Signal,Histogram,RSI,...,ATR,close_percent,high_percent,low_percent,open_percent,volume_btc_percent,volume_usd_percent,date_only,time_only,sentiment_score_avg
0,2017-02-23 03:00:00,1127.80,1132.157143,1131.022143,1131.575516,1129.226468,4.794143,4.739647,0.054497,68.191866,...,4.271071,0.000026,0.000530,0.002575,0.002575,-0.746826,-0.746819,2017-02-23,03:00:00,0.971185
1,2017-02-23 04:00:00,1128.99,1130.585714,1131.435714,1130.631637,1129.036272,4.264244,4.644566,-0.380322,56.460611,...,4.308214,-0.004519,-0.000714,-0.005967,0.000026,3.141940,3.123222,2017-02-23,04:00:00,0.971185
2,2017-02-23 05:00:00,1130.35,1129.997143,1131.622857,1130.221228,1129.030102,3.895414,4.494736,-0.599322,53.146013,...,4.239643,0.001055,-0.002675,0.000320,-0.004519,-0.625510,-0.625114,2017-02-23,05:00:00,0.971185
3,2017-02-23 06:00:00,1130.89,1130.210000,1131.600000,1130.253421,1129.206089,3.670543,4.329897,-0.659355,49.586563,...,4.097500,0.001205,0.000841,0.001811,0.001055,0.031711,0.032954,2017-02-23,06:00:00,0.971185
4,2017-02-23 07:00:00,1129.90,1130.545714,1131.910714,1130.412566,1129.430610,3.495609,4.163039,-0.667431,56.194816,...,3.909643,0.000478,0.000707,0.001427,0.001205,-0.243185,-0.242823,2017-02-23,07:00:00,0.971185

In [41]:
# take out 2 weeks worth of data for testing
start_date = '2024-01-02'
end_date = '2024-01-16'

mask = (merged_data['date'] > start_date) & (merged_data['date'] <= end_date)
weeks2 = merged_data.loc[mask]

weeks2.head(5)

,date,close,SMA_7,SMA_14,EMA_7,EMA_14,MACD,Signal,Histogram,RSI,...,ATR,close_percent,high_percent,low_percent,open_percent,volume_btc_percent,volume_usd_percent,date_only,time_only,sentiment_score_avg
59924,2024-01-01 00:00:00,42464.66,42486.947143,42502.611429,42423.379571,42448.535364,35.257027,71.300537,-36.043510,28.459555,...,191.050714,0.000312,-0.005127,-0.001083,-0.005713,0.149508,0.149867,2024-01-01,00:00:00,0.986846
59925,2024-01-01 01:00:00,42608.55,42467.554286,42487.380000,42433.699679,42450.685315,33.887642,63.817958,-29.930316,41.036871,...,201.777143,0.004524,0.004269,0.004170,0.000312,0.983559,0.992532,2024-01-01,01:00:00,0.986846
59926,2024-01-01 02:00:00,42568.02,42462.942857,42493.811429,42477.412259,42471.733940,43.906982,59.835763,-15.928781,53.834622,...,214.106429,0.003388,0.005232,0.003734,0.004524,-0.021392,-0.018076,2024-01-01,02:00:00,0.986846
59927,2024-01-01 03:00:00,42333.13,42459.461429,42504.547857,42500.064194,42484.572081,48.023366,57.473283,-9.449918,56.747803,...,206.671429,-0.000951,-0.003057,0.001962,0.003388,-0.812884,-0.813062,2024-01-01,03:00:00,0.986846
59928,2024-01-01 04:00:00,42387.48,42430.155714,42494.432143,42458.330646,42464.379804,31.963514,52.371329,-20.407815,44.517737,...,221.222857,-0.005518,-0.000725,-0.005716,-0.000951,2.438511,2.419538,2024-01-01,04:00:00,0.986846

In [37]:
# Find missing values in the data
missing_values = weeks2.isnull().sum()
missing_values

date                   0
close                  0
SMA_7                  0
SMA_14                 0
EMA_7                  0
EMA_14                 0
MACD                   0
Signal                 0
Histogram              0
RSI                    0
Upper Band             0
Lower Band             0
ATR                    0
close_percent          0
high_percent           0
low_percent            0
open_percent           0
volume_btc_percent     0
volume_usd_percent     0
date_only              0
time_only              0
sentiment_score_avg    0
dtype: int64

In [42]:
weeks2.to_csv('2weeks.csv', index=False)